name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release  # Options: Release, Debug, RelWithDebInfo, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache CMake Files
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/build
        key: cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          cmake-

    - name: Configure CMake
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: |
        ctest --output-on-failure -C ${{ env.BUILD_TYPE }}

    - name: Upload Build Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: ${{ github.workspace }}/build
